### PR TITLE
collection and level in lesson header

### PR DESCRIPTION
**Pull request by arve0**
proposal for #87 

skjermbilde 2015-03-10 kl 01 22 48
skjermbilde 2015-03-10 kl 01 23 07
skjermbilde 2015-03-10 kl 01 23 23

or black:
skjermbilde 2015-03-10 kl 00 59 38
skjermbilde 2015-03-10 kl 00 59 50
skjermbilde 2015-03-10 kl 01 00 04

### CODE REVIEW

**Comment by gahjelle** [comment]
Denne så veldig stilig ut! Tror kanskje jeg liker svart logo med hvit tekst best, men ikke veldig sterke meninger om det. Og mulig det hadde vært bedre å flyttet dette til høyre kant?

Et par tanker dog rundt hvorvidt dette er den riktige løsningen:
1. Vi blir avhengig av å lage en ny logo for hver kategori, slik at om vi legger til for eksempel Java eller Scriptcraft må vi lage nye logoer som helst skal være i samme stil.
2. Man trenger en hvis kunnskap for å tolke logoene. For eksempel, kan jeg ikke si til de på biblioteket "lag tre ekstra kopier av pythonoppgavene" for de vil ikke gjenkjenne python-logoen.
3. Vi har ikke brukt tall for å angi nivå andre steder på siten, så med denne løsningen må vi fortelle at 1 er det samme som grønn sirkel og 4 betyr svart diamant.

Jeg lurer derfor på om en bedre løsning vil være å skrive kategorien med tekst over et nivåikon? Det vil ihvertfall løse de tre punktene over.

**Comment by gahjelle** [comment]
Ah sorry, should have commented in English :P 

This looks very neat!

I do however have some thoughts around whether this is the "correct" solution:
1. We will need to create new logos for each category.
2. One needs some knowledge to interpret the logos. For instance, I can't simply tell the people at the library setting up for a code club to "make 3 extra copies of the python projects" as they will not recognize the python-logo.
3. Elsewhere, we have indicated level by icons not numbers. So now we need to tell people that 1 is the same as green circle while 4 means black diamond.

One proposal that at least fixes these three points would be to use category as text printed over level as icon.

**Comment by arve0** [comment]
1. A logo is easily created. I made these in 5 minutes using binary thresholding in fiji and subtracted background with os x preview.
2. I dont see this as a problem, as I guess they will need to find the lessons somewhere. This will preferably be from the index or stored as files somewhere. Or do the libraries use paper only?
3. Yes, we should use the level icons!

**Comment by gahjelle** [comment]
1. True, logos are easy to create, but requires some specialist knowledge. So it adds a dependency on someone like you or me :stuck_out_tongue: 

2. One actual use case: One place where I have been running a code club with both scratch and python (using print outs of projects I have originally sent them as pdfs) store old paper projects between code clubs. Then when we are running short on one project they simply make copies from the "paper original". The original pdfs are of course availble, but actually harder to find since they need to hunt through their old e-mail or know the names of the projects to find them on the web page.

The logos do look neat though. What about having text in a small font under the category icon? For instance for Scratch, we have the outline of the cat with the text SCRATCH in a small font beneath? And as a fall-back if no icon exists for a category, the text is used?

**Comment by arve0** [comment]
That should not be too hard to fix.

In list, TODO:
- text below icon
- large text fall back
- use level icon
- float right

**Comment by arve0** [comment]
skjermbilde 2015-06-09 kl 17 52 33
skjermbilde 2015-06-09 kl 17 52 15
skjermbilde 2015-06-09 kl 17 52 03
skjermbilde 2015-06-09 kl 17 52 24

Good to merge, if ok.

**Pull request merged**
