### PR TITLE
bump metalsmith-pandoc version

### PR DESCRIPTION
**Pull request by arve0**
fixes cmd.exe popups on windows

do `npm install` after merge

### CODE REVIEW

**Comment by okpedersen** [comment]
Is this tested on windows?

**Comment by arve0** [comment]
I can test it and merge.

**Comment by okpedersen** [comment]
:+1: 
I had some problems when running `npm install` after checking out. Something about pandoc-bin..

Solution:
```sh
cd codeclub_lesson_builder
rm -rf node_modules
npm install
```

**Comment by arve0** [comment]
This is not the right fix. See https://github.com/foreverjs/forever/issues/732.

**Pull request closed without merging**
