### PR TITLE
PDF

### LINKED ISSUE #73: print / pdf
Create print version of lessons with absolute URL's for downloads, such that they can be used standalone. Also check colors scratchblocks upon printing/pdf.

### PR DESCRIPTION
**Pull request by arve0**
fixes #73

### CODE REVIEW

**Comment by arve0** [comment]
skjermbilde 2015-02-26 kl 18 59 33

**Comment by arve0** [comment]
Absolute links not fixed yet, but think this is fair to merge until we have time to fix that also.

**Comment by arve0** [comment]
**NOTE:** New lodash version. Delete `node_modules` and reinstall packages with `npm install`.

**Comment by gahjelle** [comment]
This looks good and works very well!

The one tiny issue (apart from the absolute links) I noticed was that we probably want a fixed-width font in the (Python) code listings. I'll just add that as a separate issue.

**Pull request merged**
