### PR TITLE
Added teacher-activity to CSS

### PR DESCRIPTION
**Pull request by larsfk**

### CODE REVIEW

**Comment by arve0** [comment]
If this is suppose to change colors on "Læreveiledning", I propose a `.teacher` class, added to top level div.

For example in https://github.com/arve0/codeclub_lesson_builder/blob/master/layouts/lesson.jade#L39

```jade
  .col-xs-12
    if lesson  // this is README.md and an accompanying lesson is found
      .content.teacher!= contents
    else
      .content!= contents
```

**Comment by arve0** [comment]
Build failing due to bug introduced in #230, see https://github.com/linsir/markdown-it-task-checkbox/issues/4.

**Comment by arve0** [comment]
I do not quite understand what this PR is supposed to do, but I've made it so that "teacher" sections use the color you have suggested:

teacher colors

**Comment by larsfk** [comment]
The only thing I want is a section with white font and blue “background”. http://oppgaver.kidsakoder.no/beta/ <http://oppgaver.kidsakoder.no/beta/> will let all be different colors. I just want to have a section called {.teacher} that can mark when the original exercise comes with tips to the teacher.

**Comment by arve0** [comment]
I feel that adding teacher notes inside lessons is the wrong approach if they are not hidden by default. From the students approach, it adds unnescessary cruft.

Why not use the README.md? Or what about a button; "Reveal teacher notes"?

**Comment by arve0** [comment]
Oops, closed by accident.

**Comment by gahjelle** [comment]
See https://forum.kidsakoder.no/t/laererveiledninger-til-kodeklubbens-oppgaver/168

My understanding is that the teacher notes will be in a separate document.

**Comment by arve0** [comment]
OK, @larsfk, does this rhyme with your understanding?

**Comment by arve0** [comment]
OK, so according to https://github.com/kodeklubben/oppgaver/pull/384, @larsfk did **not** mean **all** sections should get another color (but I'm not sure why). To me, it makes sense to differentiate between the two (lesson vs teacher notes).

To me, two points are important:

1. Do not add unnecessary syntax.
2. Teacher action vs lesson action can be detected with heuristic.

How should we resolve this? Any ideas? What about a "teacher color theme"? Bike shedding welcome.

**Comment by larsfk** [comment]
I agree, this is a temporary solution, but we need it to find out how to make README.md the way we want. I know the BETA have some solutions, but we would be able to test that yet, I think… But the way README.md looks now is good from our (summerjob for LKK) point of view. Maybe the guys that wrote the BETA have some ideas?

**Comment by larsfk** [comment]
Okei from now on we just use .activity and not .teacher in README.md :) Examples will be sent as PR soon.

**Comment by arve0** [comment]
New palette:

teacher colors

**Pull request merged**
