### PR TITLE
pandoc => markdown-it

### LINKED ISSUE #129: pandoc vs markdown-it
I'm considering using another markdown implementation than pandoc, which will ease adding features like:

- youtube videos
- hide/show toggable content (ref #128)
- [bootstrap tabs](http://getbootstrap.com/javascript/#tabs) without using full HTML syntax

[markdown-it](https://github.com/markdown-it/markdown-it) has a [plugin system](https://www.npmjs.com/browse/keyword/markdown-it-plugin) and seems to be the goto solution nowadays.

Thoughts?

### PR DESCRIPTION
**Pull request by arve0**
fixes #129

### CODE REVIEW

**Comment by arve0** [comment]
Linkyfy seems to think file.py is links..

**Comment by arve0** [comment]
Hah, .py is a valid top domain for [Paraguay](https://en.wikipedia.org/wiki/.py)!

**Comment by arve0** [comment]
Build can be demoed [here](http://arve0.github.io/oppgaver/) to spot any discrepancies.

**Comment by arve0** [comment]
`.hint`-sections need to be fixed in css.

**Comment by gahjelle** [comment]
Very nice! Quite impressive, although I found a few small strange things:

For instance at http://arve0.github.io/oppgaver/computercraft/introduksjon_til_computercraft/introduksjon_til_computercraft.html the headlines of the yellow .tip-boxes have an extra border, and some of the code snippets, e.g. in `Steg 4` look strange. Some just have a changing background-color while a few break down completely :)

I suppose you already know that Scratch blocks are currently not rendered :)

**Comment by arve0** [comment]
Yes, the html-output is not identical, so [minor adjustments](https://github.com/arve0/codeclub_lesson_builder/commit/69fe6f397f28f7dd03efa1739658d24a69e5b3d1) to style is necessary.

The code blocks seems to be two issues, not identical HTML (scratch blocks not rendered) and trouble with indentation. [The spec](http://common mark.com) probably got the answer of how to solve it.

**Comment by arve0** [comment]
Might be the [ambiguity between indentation](http://spec.commonmark.org/0.21/#indented-code-blocks).

E.g.,
<pre>- list item

    ```js
    code();
    ```
</pre>
vs
<pre>- list item

  ```js
  code();
  ```
</pre>

**Comment by arve0** [comment]
- fixes styles in sections (extra border)
- fixed code blocks by using highlight.js directly
- inline scratchblocks can be written like this:

  ```md
  paragraph text `vent (0.5) sekunder`{.b}
  ```

**Comment by arve0** [comment]
TODO:
- markdown inline in html possible?

**Pull request merged**
