### PR TITLE
Fix broken link in format spec section of README

### PR DESCRIPTION
**Pull request by andylolz**
I don’t know if this updated link is exactly equivalent… I don’t think an exact equivalent of the formatting guide exists anymore. You could point to https://github.com/CodeClub/lesson_format/blob/4161d95e/FORMATTING.md I guess.

### CODE REVIEW

**Comment by arve0** [comment]
Thanks! :-)

**Comment by andylolz** [comment]
Relative links mean if someone is reading the README in a local clone, the link won’t work.

**Comment by arve0** [comment]
You are right. It doesn't seem to work on gh either (sure this was working the other day).

**Comment by arve0** [comment]
Ahh, `/`is relative to github.com when in issues, but to the repo for markdown files. The details... [fixed](/arve0/codeclub_lesson_builder/commit/ae5942bbca7c0855ce72faa2cabcfa3aa23a4a92)

**Comment by andylolz** [comment]
I wonder what the motivation is behind removing the protocol from hrefs? I can understand it for includes, but I don’t see why you wouldn’t force https for github links…

**Comment by arve0** [comment]
Laziness. gihub.com links are redirected to https anyhow, but you are correct in that it breaks for links not being https. To quote Tim Peters, explicit is better then implicit. I'll fix it.

**Pull request merged**
